version: '3.9'

services:

  # SERVER
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - inception
  
  # WORDPRESS
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - nginx
    networks:
      - inception

networks:
  inception:
    driver: bridge