version: '3.9'

services:

  # DATABASE
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - ~/data/mariadb:/var/lib/mysql
      - db_volume:/var/lib/mysql
    networks:
      - 42-network

  # WORDPRESS
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DOMAIN: ${DOMAIN}
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - ~/data/wordpress:/var/www/${DOMAIN}
      - wp_volume:/var/www/${DOMAIN}
    depends_on:
      - mariadb
    networks:
      - 42-network

  # SERVER
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/${DOMAIN}
    depends_on:
      - wordpress
    networks:
      - 42-network

  ##############################
  #          BONUS :^)         #
  ##############################

  # ADMINER
  adminer:
    build:
      context: requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    networks:
      - 42-network

  # STATIC WEBSITE
  website:
    build:
      context: requirements/bonus/website
    container_name: website
    restart: always
    ports:
      - "3000:3000"
    networks:
      - 42-network

  # WORDPRESS BACKUP
  backup:
    build:
      context: requirements/bonus/backup
    container_name: backup
    restart: always
    env_file: .env
    volumes:
      - ~/data/backup:/backup
      - backup_volume:/backup
    depends_on:
      - nginx
    networks:
      - 42-network

# NETWORK
networks:
  42-network:

# VOLUMES
volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${LOGIN}/data/wordpress"
  db_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${LOGIN}/data/mariadb"
  backup_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${LOGIN}/data/backup"