version: '3.9'

# NETWORK
networks:
  42-network:

# VOLUMES
volumes:
  wp_volume:
  db_volume:

services:

  # DATABASE
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - ~/data/db_volume:/var/lib/mysql
    networks:
      - 42-network

  # WORDPRESS
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DOMAIN: ${DOMAIN}
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - ~/data/wp_volume:/var/www/${DOMAIN}
    depends_on:
      - mariadb
    networks:
      - 42-network

  # SERVER
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ~/data/wp_volume:/var/www/${DOMAIN}
    depends_on:
      - wordpress
    networks:
      - 42-network

  # ADMINER
  adminer:
    build:
      context: requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    networks:
      - 42-network
  # ADMINER
  website:
    build:
      context: requirements/bonus/website
    container_name: website
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - 42-network